### ISSUE TITLE
Allow multiple clfs and param grids?

### ISSUE THREAD

**Issue by kootenpv** [rsteca/sklearn-deap#22]
I was wondering if there is a logical way to add the possibility of multiple clfs each with their own grid?

**Comment by ryanpeach** [comment]
I was just about to post something on this.

Right now, you can pass "params" a list of param grids. This is divergent, I believe, to the way that sklearn GridSearchCV works, and IMO we should simply let the user call EvolutionarySearchCV in a for loop on their own for this, as that's all we are doing anyway in the fit function.

I would just like to know the motivation for this divergence so that we stay consistent.

Also, "params" needs to be renamed "param_grid" in accordance with sklearns GridSearchCV.

**Comment by ryanpeach** [comment]
I believe this is fixed when we added optimize.py, am I correct?
